### ISSUE TITLE
rewireWorkboxInject - swSrc is not transpiled

### ISSUE THREAD

**Issue by topheman** [davejm/react-app-rewire-workbox#2]
With `rewireWorkboxInject `, the `swSrc` file is not transpiled to `swDest`, it's only copied.

This means that you can't make imports from other modules, rely on `process.env.NODE_ENV` ...

It would be great if that was possible.

Simple `config-overrides.js`

```js
const {
  rewireWorkboxInject,
  defaultInjectConfig
} = require("react-app-rewire-workbox");
const path = require("path");

module.exports = function override(originalConfig, env) {
  let config = originalConfig;

  // Workbox
  console.log("[Workbox] Preparing Service Worker");
  // Extend the default injection config with required swSrc
  const workboxConfig = {
    ...defaultInjectConfig,
    swDest: `service-worker.${env === "production" ? "prod" : "dev"}.js`,
    swSrc: path.join(__dirname, "src", "custom-sw.js")
  };
  const finalWorkboxConfig = rewireWorkboxInject(workboxConfig)(config, env);

  console.log(config);
  console.log(workboxConfig);

  return {
    ...config,
    ...finalWorkboxConfig
  };
};
```

**Comment by davejm** [comment]
Hi @topheman, this sounds like an issue more suited to the workbox webpack plugin.

I did a quick search and there does seem to be an open issue for this - https://github.com/GoogleChrome/workbox/issues/1513. Hopefully this will be addressed in the next major release of the plugin. In which case I may need to update this package as well if the API changes considerably.

**Comment by topheman** [comment]
You are right @davejm , thanks for your answer. I've subscribed to the [issue](https://github.com/GoogleChrome/workbox/issues/1513) you pointed to, I'll be following it.

**Comment by acanimal** [comment]
@topheman did you made transpilation works? Could you place a sample code?
